### ISSUE TITLE
Can't build: 

### ISSUE THREAD

**Issue by roddle** [mindok/hugodeploy#5]
not sure what to do here, I'm following along with the installation and after attempting go build I get this error:
# .   github.com/mindok/hugodeploy/deploy

deploy/ftp.go:88: cannot use config (type tls.Config) as type *tls.Config in argument to f.ftp.AuthTLS

**Comment by mindok** [comment]
Hi @roddle - A couple of quick questions:
1. What version of go are you using? I'll be honest - I'm still on an older version - (1.4.2 - I know... - I haven't looked at this code this year). I'll install whatever version you are on and rebuild against that.
2. Could you please supply the full error message - it looks like github has chopped off a bit.

Apologies for not getting back to you sooner...

Thanks,

**Comment by roddle** [comment]
No worries about how long it took to get back, I'm happy just manually deploying for now.
1. I'm using go 1.7.3 darwin/amd64 on Mac OS X Sierra 10.12
2. It looks to me that the full error message is printed, just two lines:
   
   # github.com/mindok/hugodeploy/deploy
   
   deploy/ftp.go:88: cannot use config (type tls.Config) as type *tls.Config in argument to f.ftp.AuthTLS

**Comment by mindok** [comment]
ok - I can see the problem. Back in July it looks like dutchcoders/goftp package had a change of signature in the method to access tls.Config by reference rather than by value. If you want a quick fix you could edit the breaking line to pass a pointer to the config variable - ie pass as &config rather than config. So line 88 would read :
`if err = f.ftp.AuthTLS(&config); err != nil {`

I'll pull down an update to goftp, fix and update the repository here over the next day or two - I won't have time to properly test right now...

**Comment by mindok** [comment]
Updated type and committed.
