### ISSUE TITLE
Can't override default sourceDir

### ISSUE THREAD

**Issue by hfoffani** [mindok/hugodeploy#9]
Hi,

In a hugodeploy.toml config type I couldn't make the program set the sourceDir value. I have to let the program pick the files from the "publish" directory. I tried both relative and absolute values.

By the way, I think there is a mismatch in the source code between the documented default value `cmd/init.go:281` and the actual expected value `cmd/root.go:81`

**Comment by mindok** [comment]
I use the attached (with sensitive bits redacted) config file - yaml rather than toml. Setting sourceDir definitely works for me as I don't use the default. You are right about the mismatch - it shouldn't matter as it will read what's in the config file (generated by init) if it exists and fall back to what's in root..go:81 if it isn't set in the config file, but I'll make them consistent anyway.

If you set verbose: true in the config file, or use -v flag on the command line, you will be able to see exactly what settings are in play. If you use -d you will see whether the values are set through command line or config file.

Let me know how you go. If you continue to have problems, upload your toml file (with sensitive bits removed) and I'll test against that rather than the yaml file I use.
[hugodeploy.works.yaml.zip](https://github.com/mindok/hugodeploy/files/889078/hugodeploy.works.yaml.zip)

**Comment by hfoffani** [comment]
Thanks for hint about -v.

I think I know what is going on. It might be related with .toml

If the `[ftp]` entry is at the top of the .toml config file, then it fails to load the rest of the variables. Or actually it reads them but assigning them to the `ftp` namespace.
 
```sh
webhugo $ cat hugodeploy.toml
# HugoDeploy Configuration File

[ftp]
    host = "ftp.decastex.com"
    user = "UUUUU"
    pwd = "XXXXX"
    rootdir = "/html/"

sourceDir = "/Users/hernan/Documents/decastex-web/webhugo/public"
deployRecordDir = "/Users/hernan/Documents/decastex-web/webhugo/deployed"

webhugo $ hugodeploy preview -v
Using config file: /Users/hernan/Documents/decastex-web/webhugo/hugodeploy.toml
INFO 2017/04/03 11:17:39 Listing Config:
INFO 2017/04/03 11:17:39 ftp.user : UUUUU
INFO 2017/04/03 11:17:39 ftp.rootdir : /html/
INFO 2017/04/03 11:17:39 sourcedir : publish
INFO 2017/04/03 11:17:39 deployrecorddir : deployed
INFO 2017/04/03 11:17:39 dontminify : false
INFO 2017/04/03 11:17:39 skipfiles : [.git* .DS_Store]
INFO 2017/04/03 11:17:39 verbose : true
INFO 2017/04/03 11:17:39 ftp.host : ftp.decastex.com
INFO 2017/04/03 11:17:39 ftp.pwd : XXXXX
INFO 2017/04/03 11:17:39 ftp.sourcedir : /Users/hernan/Documents/decastex-web/webhugo/public
INFO 2017/04/03 11:17:39 debug : false
INFO 2017/04/03 11:17:39 ftp.deployrecorddir : /Users/hernan/Documents/decastex-web/webhugo/deployed
INFO 2017/04/03 11:17:39 Checking Source Dir exists:  publish
CRITICAL 2017/04/03 11:17:39 Source Dir does not exist publish
webhugo $ 
```

However if I move the global settings to the top, hugodeploy reads them correctly:

```sh
webhugo $ cat hugodeploy.toml
# HugoDeploy Configuration File

sourceDir = "/Users/hernan/Documents/decastex-web/webhugo/public"
deployRecordDir = "/Users/hernan/Documents/decastex-web/webhugo/deployed"

[ftp]
    host = "ftp.decastex.com"
    user = "UUUUU"
    pwd = "XXXXX"
    rootdir = "/html/"

webhugo $ hugodeploy preview -v
Using config file: /Users/hernan/Documents/decastex-web/webhugo/hugodeploy.toml
INFO 2017/04/03 11:22:59 Listing Config:
INFO 2017/04/03 11:22:59 ftp.host : ftp.decastex.com
INFO 2017/04/03 11:22:59 ftp.user : UUUUU
INFO 2017/04/03 11:22:59 ftp.pwd : XXXXX
INFO 2017/04/03 11:22:59 ftp.rootdir : /html/
INFO 2017/04/03 11:22:59 debug : false
INFO 2017/04/03 11:22:59 skipfiles : [.git* .DS_Store]
INFO 2017/04/03 11:22:59 dontminify : false
INFO 2017/04/03 11:22:59 verbose : true
INFO 2017/04/03 11:22:59 sourcedir : /Users/hernan/Documents/decastex-web/webhugo/public
INFO 2017/04/03 11:22:59 deployrecorddir : /Users/hernan/Documents/decastex-web/webhugo/deployed
INFO 2017/04/03 11:22:59 Checking Source Dir exists:  /Users/hernan/Documents/decastex-web/webhugo/public
INFO 2017/04/03 11:22:59 Preview: Source Dir Good:  /Users/hernan/Documents/decastex-web/webhugo/public
INFO 2017/04/03 11:22:59 Checking Deploy Dir exists:  /Users/hernan/Documents/decastex-web/webhugo/deployed
INFO 2017/04/03 11:22:59 Preview: Deploy Record Dir Good:  /Users/hernan/Documents/decastex-web/webhugo/deployed
Comparing Dst:  /Users/hernan/Documents/decastex-web/webhugo/deployed  With Src:  /Users/hernan/Docu...
... etc ...
webhugo $ 
```

**Comment by hfoffani** [comment]
I can confirm that this only happens with `.toml`.

It's my fault, now I see it's a limitation of `toml` format as documented in https://npf.io/2014/08/intro-to-toml/

Thanks!

**Comment by mindok** [comment]
Well spotted - so I guess a few choices going forward:
1. Update README to highlight the issue
2. Desupport toml
3. Update init.go to generate a valid toml structure with hints (maybe with an init flag option to generate toml rather than yaml)
4. Modify the settings structure to create a high-level wrapper around sourceDir etc...

Probably 1, then 3 are preferred for me

**Comment by hfoffani** [comment]
1 is enough I think. 3 would be a great addition.

**Comment by mindok** [comment]
ok, I've updated the readme for now. Thanks for finding the problem. I'll close for now. If anyone else runs into the same issue I'll fix up the init.
